language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - pecl install uopz
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

jobs:
  include:

    - stage: dependencies
      script:
        - vendor/bin/composer-require-checker --config-file=.require.json

    - stage: coding standards
      script:
        - vendor/bin/phpcs --standard=phpcs.xml src tests

    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)

git:
  depth: 5

group: travis_latest
